### ISSUE TITLE
Completed Step Behavior

### ISSUE THREAD

**Issue by likeanormaldude** [colbymillerdev/react-native-progress-steps#12]
I was looking to your code and i was hoping if some modifications can be done on steps items behavior on the top, regarding to:

- Change default text or icon (maybe integrate it with react-native-vector-icons) in both completed step or current step and not just the current label below it.
- I was looking on the documentation and couldn't find any topic on how to set a custom step as active manually
- Is there a way to make the steps items touchables and delegate onpress listeners to them?

**Comment by colbymillerdev** [comment]
Hello -

Thanks so much for your great suggestions! Please see below for my comments:

- I will be looking into adding the functionality to change the step text to icons for a future release.

- This has now been fixed in the most recent version of the package. You can add the `activeStep` prop to the `<ProgressSteps />` component.

- There isn't any current functionality to allow the step icons to be touchable. However I will also consider implementing this in a future release.

Pull requests are always welcome for the project if you want to take a shot at implementing a feature :)
