### ISSUE TITLE
Rockwell Font

### ISSUE THREAD

**Issue by yuskamal** [colbymillerdev/react-native-progress-steps#2]
fontFamily "rockwell" is not a system font and has not been loaded through Font.loadAsync

**Comment by colbymillerdev** [comment]
I believe this is an issue with using Expo and custom fonts, not this component. However, "rockwell" should not be the default font in this component due to these issues. So I will make that fix later tonight.

A quick fix for right now is to just pass a system recognized font to the ProgressSteps component using the `labelFontFamily` prop.

**Comment by colbymillerdev** [comment]
I believe this is an issue with using Expo and custom fonts, not this component. However, "rockwell" should not be the default font in this component due to these issues. So I will make that fix later tonight.

A quick fix for right now is to just pass a system recognized font to the ProgressSteps component using the `labelFontFamily` prop.

Thanks for bringing this issue to my attention!

**Comment by colbymillerdev** [comment]
The "rockwell" font has been removed as the default, so this issue should be resolved. 

If you don't want to use the iOS/Android default font, set a new font using the `labelFontFamily` prop on the `ProgressSteps` component.

This repo has a good list of available fonts for React Native: [https://github.com/react-native-training/react-native-fonts](https://github.com/react-native-training/react-native-fonts)
