### ISSUE TITLE
FlatList into progressStep component

### ISSUE THREAD

**Issue by rauan100** [colbymillerdev/react-native-progress-steps#22]
I have a problem when a use a flatlist in ProgressStep. I think this problem solve, if you use SafeAreaView instead of scrollView in ProgressStep.

I am use react-native 0.61.5.

**Comment by berserkerChrist** [comment]
I used SafeAreaView instead of ScrollView in ProgressStep component but didn't work. Any ideas on how to solve this? 

I'm getting this warning:

VirtualizedLists should never be nested inside plain ScrollViews with the same orientation - use another VirtualizedList-backed container instead.

**Comment by rauan100** [comment]
It Works for me, can you send me the render code? Please

**Comment by colbymillerdev** [comment]
@berserkerChrist Seems that warning started happening with a recent version of React Native. It is being thrown because the `FlatList` and `ScrollView` have a redundant scrolling behavior (In this case, both are scrolling vertically).

I can't remove `ScrollView` because it will break the scrolling behavior for anyone not using a `FlatList` in their implementation.

**Comment by dl-husky73** [comment]
Can I ask if there was ever a resolution of the best way to use a Flatlist in the steps without the virtualized list view?
