### ISSUE TITLE
Label or Title text size

### ISSUE THREAD

**Issue by ninoespina36** [colbymillerdev/react-native-progress-steps#55]
Hello, is there any prop to change the font size of the ProgressStep label? I don't see it on the documentation. thank you

**Comment by colbymillerdev** [comment]
Hi @ninoespina36 - The label font size is not currently a customizable option. I will work on adding a prop so that this can be accomplished. Thanks for opening this issue!

**Comment by saravanasd** [comment]
If the label font size is customizable it will be very usefull
Thanks @colbymillerdev

**Comment by colbymillerdev** [comment]
Hello @ninoespina36 - Sorry for the delay with getting this added, but it is now available in the newest release of the package (v1.3.4). You can use the `labelFontSize` prop to change the size of the step icon labels. An `activeLabelFontSize` prop has also been added so that the active step label can be set to a different size than the others.

https://github.com/colbymillerdev/react-native-progress-steps/releases/tag/v1.3.4
